---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-pvc
  namespace: force
  labels:
    app: force
    tier: analytics
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi