---
apiVersion: v1
kind: Service
metadata:
  name: side-prediction
  namespace: force
  labels:
    app: force
    tier: analytics
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: http
  selector:
    name: prediction-service