package com.boxyware.force

case class Subject(
  name: String,
  midichlorian: Double,
  species: String,
  gender: String,
  homeworld: String,
  side: String
)

object TestDataset {

  val subjects = Seq(
    Subject("Anakin Skywalker/Darth Vader", 27700, "human", "male", "Tatooine", "Sith"),
    Subject("Darth Sidious", 20500, "human", "male", "Naboo", "Sith"),
    Subject("Yoda", 17700, "unknown (Yoda's species)", "male", "unknown", "Jedi"),
    Subject("Luke Skywalker", 14500, "human", "male", "Tatooine", "Jedi"),
    Subject("Leia Organa Solo", 14500, "human", "female", "Alderaan", "None"),
    Subject("Aenon Jurtis", 14200, "zabrak", "male", "Iridonia", "Jedi"),
    Subject("Shintor Beerus", 13900, "rodian", "male", "Rodia", "Jedi"),
    Subject("Ben (Jhon) Skywalker", 13700, "human", "male", "Coruscant", "Jedi"),
    Subject("Anakin Solo", 13700, "human", "male", "Coruscant", "Jedi"),
    Subject("Count Dooku/Darth Tyranus", 13500, "human", "male", "Serenno", "Sith"),
    Subject("Obi-Wan Kenobi", 13400, "human", "male", "Stewjon", "Jedi"),
    Subject("Kaja Sinis", 13250, "twi'lek", "male", "Ryloth", "Jedi"),
    Subject("Kyle Katarn", 12200, "human", "male", "Sulon", "Jedi"),
    Subject("Mace Windu", 12000, "human", "male", "Haruun Kal", "Jedi"),
    Subject("Darth Maul", 12000, "zabrak", "male", "Dathomir", "Sith"),
    Subject("General Grievous", 11900, "kaleesh", "male", "Kalee", "Sith"),
    Subject("Kit Fisto", 11800, "nautolan", "male", "Glee Anselm", "Jedi"),
    Subject("Exar Kun", 11700, "human", "male", "Yavin 4", "Sith"),
    Subject("Yaddle", 11300, "unknown (Yoda's species)", "female", "unknown", "Jedi"),
    Subject("Xanatos'", 11300, "human", "male", "Telos IV", "Jedi"),
    Subject("Plo Koon", 11100, "kel dor", "male", "Dorin", "Jedi"),
    Subject("Mara Jade", 11000, "human", "female", "Coruscant", "Jedi"),
    Subject("Darth Malak", 10800, "human", "male", "Quelii", "Sith"),
    Subject("Corran Horn", 10700, "human", "male", "Corellia", "Jedi"),
    Subject("Ki Adi Mundu", 10600, "cerean", "male", "Cerea", "Jedi"),
    Subject("Darth Bane", 10500, "human", "male", "Apatros", "Sith"),
    Subject("Joruus C'baoth", 10350, "human", "male", "Wayland", "Sith"),
    Subject("Darth Imperius", 10300, "human", "male", "Korriban", "Sith"),
    Subject("Shaak Ti", 10300, "togruta", "female", "Shili", "Jedi"),
    Subject("Darth Revan", 10200, "human", "male", "Outer Rim Territories", "Sith"),
    Subject("Aalya Secura", 10000, "twi'lek", "female", "Ryloth", "Jedi"),
    Subject("Qui-Gon Jinn", 10000, "human", "male", "Coruscant", "Jedi"),
    Subject("Assajj Ventress", 9600, "zabrak", "female", "Dathomir", "Sith"),
    Subject("Naga Sadow", 9400, "human", "male", "Ziost", "Sith"),
    Subject("Jacen Solo/Darth Caedus", 9000, "human ", "male", "Coruscant", "Sith"),
    Subject("Jaina Solo", 9000, "human", "female", "Coruscant", "Jedi"),
    Subject("Tionne Solusar", 8500, "human", "female", "Rindao", "Jedi"),
    Subject("Chewbacca", 7200, "wookiee", "male", "Kashyyyk", "None"),
    Subject("Liv'trai", 7100, "Twi'lek", "female", "Tython", "Jedi"),
    Subject("Aurra Sing", 7000, "Palliduvan", "female", "Nar Shaddaa", "None"),
    Subject("Padme Amidala", 4700, "human", "female", "Naboo", "None"),
    Subject("Danni Quee", 4500, "human", "female", "Commenor", "Jedi"),
    Subject("Beru Lars", 3700, "human", "female", "Tatooine", "None"),
    Subject("Shmi Skywalker Lars", 3300, "human", "female", "Tatooine", "None"),
    Subject("Lando Calsarrian", 3300, "human", "male", "Socorro", "None"),
    Subject("Boba Fett", 1500, "human", "male", "Kamino", "None"),
    Subject("Han Solo", 1500, "human", "male", "Corellia", "None"),
    Subject("Jango Fett", 1500, "human", "male", "Concord Dawn", "None"),
    Subject("Owen Lars", 1500, "human", "male", "Tatooine", "None"))
}